### ISSUE TITLE
Filestructure of input data

### ISSUE THREAD

**Issue by alketh** [r4atlantis/atlantisom#19]
Currently, there seems to be a bit confusion (at least for my part) on how we want to handle our input data. As stated earlier there are multiple folders for many atlantis model (mainfolder, outputfolder). Therefore, constructing input-sources with a predefined directory should result in serious problems. However, I don't want to break the current code or recreate the stuff people have already written a few minutes ago... Therefore, I suggest that we try to make a decision together and change the code accordingly.

1. Include a dir argument in each function.
2. Construct the input destination without a predefined directory (I highly recommend this solution).

**Comment by allanhicks** [comment]
Thanks Alex. I agree that it is time to discuss the current state and how functions are expecting input. It may be useful to have some flow charts, or at least define inputs and outputs from functions and the flow of data through and between the functions.

**Comment by kellijohnson** [comment]
I recommend we use `R` objects instead, where we can. Meaning that instead of calling `load_bps` inside `load_nc` we pass the `bps` data as an object in the function arguments for `load_nc`. This will also help facilitate people being able to construct fake inputs rather than actual Atlantis run files if they want. I am not sure how much people plan on working on this tonight but if you have questions feel free to email me offline or post a response. I will be away from my email for a bit, but working on this later tonight and in the morning.
