### ISSUE TITLE
load_meta challenge

### ISSUE THREAD

**Issue by hodgsone** [r4atlantis/atlantisom#20]
I am trying to use the load_meta function because I need outputs from the run.prm in order to do the stage2age calculations (I need the time step of outputs). 

The function -- on line 46 appears to create the 'file.log' variable, but it has two character strings -- because in my run folder there are actually two log files, log.txt and log2.txt, and so the same thing happened for the 'file.prm' because I also have two run prms in the folder --- I think an old model's file and mine. I am not sure if the best thing is to make sure that users only have one file in the folder, but some of the files I have are replicate files that have been saved from old runs and I am not sure I want to delete them (maybe I am crazy).

Not sure how to fix this to make sure the correct file is selected among the multiple copies with similar names.

I get:
` > file.prm `

`[1] "/Users/ehodgson/Dropbox/UW/files/EH10212015_pH2013_AllOn_mort0.1/CalCurrentV3_run.prm" `
`[2] "/Users/ehodgson/Dropbox/UW/files/EH10212015_pH2013_AllOn_mort0.1/VMPArun.prm"  `

and
` > file.log`

`[1] "/Users/ehodgson/Dropbox/UW/files/EH10212015_pH2013_AllOn_mort0.1/log.txt" `
`[2] "/Users/ehodgson/Dropbox/UW/files/EH10212015_pH2013_AllOn_mort0.1/log2.txt" `

**Comment by kellijohnson** [comment]
Fixed with 74737df2710fcb0fa4eab6423da83b2737a1eea2, which uses the last file found in the search string. This might be an issue with prm files, but if so users can change the name such that the prm they want is the last file listed. @hodgsone if you have other ideas on how to find the best file I am happy to change it, but I am closing this issue for now. please feel free to reopen rather than starting a new issue.
