### ISSUE TITLE
Change run_ to convert_

### ISSUE THREAD

**Issue by slucey** [r4atlantis/atlantisom#24]
The function name run_atlantis is a little cryptic.  I think we should consider calling it convert_atlantis instead.  Run_atlantis infers that the function calls Atlantis and runs it which of course this function does not do.  Instead it converts the Atlantis output into usable R output.  The change should have minor impact on the rest of the code but didn't want to change it without consulting the group.

**Comment by kellijohnson** [comment]
It is a trivial matter, but `run_` is shorter to type. I agree that it implies that we are running an Atlantis model, so I am up for changing the second half, such as `run_data` or something along those lines, so that when we compile all the sampling functions we can then have a `run_sample`. The `run_` was meant to be carried through to other functions within the developing package, therefore `convert` does not make sense for all applications.

**Comment by sgaichas** [comment]
How about calling it `run_true`  or `run_truth` ?

**Comment by kellijohnson** [comment]
changed to run_truth with 82740f089dbb6fc2507595997463ed81f23327d1, still need to document with roxygen

**Comment by kellijohnson** [comment]
roxygen updated with 9a528be52fbb1a0498db13fb28f633a4e087ea97
